# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build & Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish (Linux)
      run: dotnet publish PlexMetadataConfigurer --runtime linux-x64
    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: plexMetadataConfigurer_linux_x64
        path: /home/runner/work/PlexMetadataConfigurer/PlexMetadataConfigurer/PlexMetadataConfigurer/bin/Release/net9.0/linux-x64/publish/
    - name: Publish (Windows)
      run: dotnet publish PlexMetadataConfigurer --runtime win-x64
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: plexMetadataConfigurer_windows_x64
        path: /home/runner/work/PlexMetadataConfigurer/PlexMetadataConfigurer/PlexMetadataConfigurer/bin/Release/net9.0/win-x64/publish/        
